casir_messenger/urls.py
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.contrib import admin
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from django.contrib.auth.views import login

urlpatterns = patterns('',
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^403/$', TemplateView.as_view(template_name="403.html")),
                       url(r'^404/$', TemplateView.as_view(template_name="404.html")),
                       url(r'^500/$', TemplateView.as_view(template_name="500.html")),
                       url(r'^503/$', TemplateView.as_view(template_name="503.html")),
                       url(r'^membre/', include("members.urls", namespace="members")),
                       url(r'', include("promotion.urls", namespace="promotion")),

                       # Example template
                       url(r'^dashboard/index/$', TemplateView.as_view(template_name="dashboard/index.html")),
                       )

if settings.DEBUG:
    # Add the Debug Toolbar's URLs to the project's URLconf
    import debug_toolbar
    urlpatterns += patterns('', url(r'^__debug__/', include(debug_toolbar.urls)),)

    # In DEBUG mode, serve media files through Django.
    urlpatterns += staticfiles_urlpatterns()
    # Remove leading and trailing slashes so the regex matches.
    media_url = settings.MEDIA_URL.lstrip('/').rstrip('/')
    urlpatterns += patterns('', url(r'^%s/(?P<path>.*)$' % media_url, 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),)

members/urls.py
from django.conf.urls import patterns, url


urlpatterns = patterns('',
                       url(r'^se-deconnecter/$', 'django.contrib.auth.views.logout', {'next_page': "/"}, name="logout"),
                    )

promotion/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('promotion.views',
                       url('^$', 'index', name="index"))

dashboard/models.py
from django.db import models

# Create your models here.

members/models.py
from django.db import models

class Utilisateur(models.Model):
    login = models.TextField()
    motDePasse = models.TextField()
    mail = models.TextField()
    
    
class StatutAmitie(models.Model):
    idUserAppelant = models.ForeignKey('Utilisateur', related_name = 'idUserAppelant')
    idUserAppele = models.ForeignKey('Utilisateur', related_name = 'idUserAppele')
    etatAmitie = models.BooleanField(default = False)

messagerie/models.py
from django.db import models

class Message(models.Model):
    message = models.TextField()
    date = models.DateTimeField(auto_now = True)
    etatLu = models.BooleanField(default = True)
    duree = models.PositiveSmallIntegerField()
    idExpediteur = models.ForeignKey(User, related_name = 'idExpediteur')
    idDestinataire = models.ForeignKey(User, related_name = 'idDestinataire')
    idPj = models.ForeignKey('PieceJointe')

promotion/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

    

members/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm as DjangoAuthenticationForm  
from django.contrib.auth.models import User

class AuthenticationForm(DjangoAuthenticationForm):
    username = forms.CharField(label="Nom d'utilisateur", max_length=254, widget=forms.TextInput(attrs={"class": "form-control", 'placeholder':'Nom d\'utilisateur'}))
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={"class": "form-control", 'placeholder':'Mot de passe'}))
  
  
class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label="Nom d'utilisateur", max_length=254, widget=forms.TextInput(attrs={"class": "form-control", 'placeholder':'Nom d\'utilisateur'}))
    email = forms.EmailField(label="Nom d'utilisateur", max_length=254, widget=forms.TextInput(attrs={"class": "form-control", 'placeholder':'Email'}))
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput(attrs={"class": "form-control", 'placeholder':'Mot de passe'}))

     
    class Meta:
        model=User
        fields = ("username","email", "password")

dashboard/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render_to_response('dashboard/templates/dashboard/index.html')

members/views.py
from django.shortcuts import render

# Create your views here.

messagerie/views.py
from django.shortcuts import render

# Create your views here.

promotion/views.py
from django.shortcuts import render
from django.contrib.auth import login as auth_login
from django.contrib.auth import authenticate
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from members.forms import AuthenticationForm
from members.forms import RegistrationForm


def index(request):

    messaging_url = "/dashboard/index/" # Are we going to a static template ?

    authentication_form = AuthenticationForm(request, prefix='authentication')
    registration_form = RegistrationForm(prefix='registration')
    if request.method == "POST":
        user = None
        
        if "login" in request.POST:
            authentication_form = AuthenticationForm(request, data=request.POST, prefix='authentication')
            if authentication_form.is_valid():
                # Okay, security check complete. Get the user.
                user = authentication_form.get_user()
        elif "register" in request.POST:
            registration_form = RegistrationForm(request.POST, prefix='registration')
            if registration_form.is_valid():
                user = registration_form.save()
                user.set_password(registration_form.cleaned_data["password"])
                user.save()
                user = authenticate(username=registration_form.cleaned_data["username"], password=registration_form.cleaned_data["password"])
                
                
#         if registration_form.is_valid():
#             user = authentication_form.get_user()
#             admin.site.register(user)
        if user is not None:
            auth_login(request, user)
            return HttpResponseRedirect(messaging_url)

    context = {
        'authentication_form': authentication_form,
        'registration_form': registration_form,
    }

    return render(request, "promotion/index.html", context)

casir_messenger/templates/503.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<div class="row">
		<div class="col-sm-12">
		
		<div class="panel panel-warning">
			  <div class="panel-heading">
			    <h3 class="panel-title">Attention</h3>
			  </div>
			  <div class="panel-body">
			    	Maintenance en cours.
			  </div>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

casir_messenger/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
    <head>
        {% block head %}
            <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	        <meta name="created" content="{% now "jS M Y h:i" %}" />
	        <meta name="description" content="{% block description %}{% endblock %}" />
	        <meta name="keywords" content="{% block keywords %}{% endblock %}" />
	        <meta name="viewport" content="{% block viewport %}width=device-width, initial-scale=1{% endblock %}" />
		    <meta http-equiv="X-UA-Compatible" content="IE=edge">
		    
            <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon" />
            
            <title>{% block title %}Casir messenger &mdash; {% block page_title %}{% endblock page_title %}{% endblock title %}</title>
            
			 <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
			    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
			    <!--[if lt IE 9]>
			      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
			      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		    <![endif]-->
        {% endblock head %}

        {% block mainstyles %}
        	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
        	<link href="{% static 'css/bootstrap-theme.css' %}" rel="stylesheet">
        	<link href="{% static 'css/common.css' %}" rel="stylesheet">
        {% endblock mainstyles %}
        
        {# Additional CSS - specific to certain pages #}
        {% block extrastyles %}{% endblock %}
        
        {% block extrahead %}{% endblock %}
        
        {% block cdn_scripts %}
            <!-- jQuery -->
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        	<script src="{% static 'js/bootstrap.min.js' %}"></script>
        {% endblock %}

        {# Local scripts #}
        {% block scripts %}
        {% endblock %}
        
        {# Additional JS scripts #}
        {% block extrascripts %}{% endblock %}
    </head>
    
    <body id="{% block body_id %}{% endblock body_id %}" class="{% block body_class %}{% endblock body_class %}">
        <div id="wrap">
            {% block header %}
	            <nav class="navbar navbar-default">
			      <div class="container-fluid">
			        <div class="navbar-header">
			          <a class="navbar-brand" href="#">CASIR Messenger</a>
			        </div>
                    {% if user.is_authenticated %}
                        <div class="collapse navbar-collapse pull-right">
                              <ul class="nav navbar-nav">
                                <li class="dropdown">
                                  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Connecté en tant que {{ user.username }} <span class="caret"></span></a>
                                  <ul class="dropdown-menu" role="menu">
                                    <li><a href="{%  url "members:logout" %}">Se déconnecter</a></li>
                                  </ul>
                                </li>
                              </ul>
                        </div><!-- /.navbar-collapse -->
                    {%  endif %}
			      </div>
			    </nav>
        	{% endblock header %}
    
        	{% block content %}
        	{% endblock content %}
            
        </div>
        <div class="footer">
            {% block footer %}
            {% endblock footer %}
        </div>
    </body>
</html>

dashboard/templates/dashboard/base.html
{%  extends 'base.html' %}
{% load staticfiles %}

{% block extrastyles %}<link href="{% static 'css/dashboard.css' %}" rel="stylesheet">{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12">
			<div class="jumbotron">
			  <h1>Dashboard</h1>
			  <p>Vous pouvez gérer vos messages et vos amis depuis cet espace !</p>
			</div>
		</div>
	</div>

    {%  block dashboard_inner %}
    {% endblock dashboard_inner %}
</div>
{% endblock content %}

dashboard/templates/dashboard/index.html
{% extends 'dashboard/base.html' %}
{% load staticfiles %}

{% block body_id %}id_dashboard_index{% endblock body_id %}

{%  block dashboard_inner %}
<div class="row">
    <div class="col-sm-3 col-md-2">
        <div class="panel panel-default">
          <div class="panel-heading">Mes amis</div>
                <ul class="list-group">
                    <li class="list-group-item"><a href="#TODO" title="Voir les détails de Maman">Maman</a></li>
                    <li class="list-group-item"><a href="#TODO" title="Voir les détails de LGerb">LGerb</a></li>
                </ul>

                  <div class="panel-body">
                      <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#id_add_friend_modal">Ajouter un ami</button>
                  </div>
        </div>
    </div>

    <div class="col-sm-9 col-md-10">
        <div class="row">
            <div class="col-sm-3 col-md-2"><button type="button" class="btn btn-success" title="Nouveau message" data-toggle="modal" data-target="#id_new_message_modal">Nouveau message</button></div>
            <div class="col-sm-3 col-md-2"><button type="button" class="btn btn-success" title="Demandes en attente" data-toggle="modal" data-target="#id_waiting_friends_modal">Demandes en attente <span class="badge">4</span></button></div>
        </div>

        <div class="row" id="id_messages_list_row">
            <div class="col-sm-12">
              <table class="table table-hover">
                  <thead>
                    <tr>
                      <th>Pseudo</th>
                      <th>Date</th>
                      <th>Etat</th>
                    </tr>
                  </thead>

                  <tbody>
                    <tr class="success">
                      <td>LGerb</td>
                      <td>01/01/2015</td>
                      <td>Non lu</td>
                    </tr>
                    <tr class="success">
                      <td>LGerb</td>
                      <td>01/01/2015</td>
                      <td>Non lu</td>
                    </tr>

                    <tr class="success">
                      <td>LGerb</td>
                      <td>01/01/2015</td>
                      <td>Non lu</td>
                    </tr>
                    <tr class="success">
                      <td>LGerb</td>
                      <td>01/01/2015</td>
                      <td>Non lu</td>
                    </tr>
                    <tr class="danger">
                      <td>Maman</td>
                      <td>01/01/2015</td>
                      <td>Lu</td>
                    </tr>

                  </tbody>
              </table>

                <nav class="pull-right">
                  <ul class="pagination">
                    <li>
                      <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                      </a>
                    </li>
                    <li><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li>
                      <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                      </a>
                    </li>
                  </ul>
                </nav>
            </div>
        </div>
    </div>

<div class="modal fade" id="id_add_friend_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Ajouter un ami</h4>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
                      <thead>
                       </tbody>
                  </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-success">Envoyer une demande d'ajout</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal fade" id="id_waiting_friends_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Demandes d'ajout en attente</h4>
      </div>
      <div class="modal-body">
        <table class="table table-hover">
                      <thead>
                        <tr>
                          <th colspan="2">Pseudo</th>
                        </tr>
                      </thead>

                      <tbody>
                        <tr>
                          <td class="success">johan_iut</td>
                          <td><input type="checkbox"></td>
                        </tr>

                        <tr>
                          <td class="success">johan_iut2</td>
                          <td><input type="checkbox"></td>
                        </tr>
                        <tr>
                          <td class="success">johan_iut3</td>
                          <td><input type="checkbox"></td>
                        </tr>

                      </tbody>
                  </table>
      </div>
      <div class="modal-footer">
          <button type="button" class="btn btn-danger">Refuser la/les demandes</button>
          <button type="button" class="btn btn-success">Accepter la/les demandes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

{%  endblock dashboard_inner %}

promotion/templates/promotion/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body_id %}id_index{% endblock body_id %}

{% block extrastyles %}<link href="{% static 'css/index.css' %}" rel="stylesheet">{% endblock %}

{% block content %}
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-6">
			<div class="jumbotron">
			  <h2>Bienvenue sur CASIR Messenger</h2>
			  <h3>CASIR Messenger, la messagerie éphémère !</h3>
			  <p><a class="btn btn-primary btn-lg" href="#TODO" role="button">Comment ça marche ?</a></p>
			</div>
		</div>
		<div class="col-lg-offset-1 col-sm-4">
            <div class="row">
                <div class="col-sm-12">
                    <form method='POST' action ="." >
                        {% csrf_token %}
                          {% for field in authentication_form %}
                            <div class="form-group {%  if field.errors %}has-error{% endif %}">
                                 {%  if field.errors %}
                                    <label class="control-label">{{ field.label }}: {%  for error in field.errors %}{{ error }} {% endfor %}</label>
                                {% endif %}
                                {{ field }}
                            </div>
                          {% endfor %}
                      <button type="submit" class="btn btn-primary btn-block btn-lg" name="login">Se connecter</button>
                    </form>
                </div>
            <div>
            <div class="row">
                <div class="col-sm-12">
                    <h3>Nouveau sur CASIR Messenger</h3>
                    <form method='POST' action ="" >
                        {% csrf_token %}
                          {% for field in registration_form %}
                            <div class="form-group {%  if field.errors %}has-error{% endif %}">
                                 {%  if field.errors %}
                                    <label class="control-label">{{ field.label }}: {%  for error in field.errors %}{{ error }} {% endfor %}</label>
                                {% endif %}
                                {{ field }}
                            </div>
                          {% endfor %}
                      <button type="submit" class="btn btn-primary btn-block btn-lg" name="register">S'inscrire</button>
                    </form>
                </div>
            </div>
        </div>
	</div>
</div>
{% endblock content %}